apps:
  youdaodict:
    border_color: null
    dark_title_bar: true
    enabled: true
    text_color: null
    title_bar_color: null
    window_theme: DarkMode_CFD
settings:
  monitor_interval: 2
  run_at_startup: false
  start_minimized: true
